tracing:
    zipkin:
        enabled: true
        sampler:
            probability: 1
micronaut:
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
stackdriver:
    project-id: "wise-coyote-827"